server:
    port: 8088
spring:
    #给项目来个名字
    application:
        name: boot-rabbitmq
    #配置rabbitMq 服务器
    rabbitmq:
        host: 192.168.86.128
        port: 5672
        username: ems
        password: 123
        #虚拟host 可以不设置,使用server默认host
        virtual-host: ems